apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.env.APP_NAME }}
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.env.APP_NAME }}